#!/bin/bash

fzf_bh() {
    __sel="$(brow -q "title,url" -c | fzf)"
    [[ "$__sel" =~ http.*$ ]] && echo "$BASH_REMATCH" | xargs -r -d '\n' brave
}

dmenu_bh() {
    # for zsh:
    # setopt local_options BASH_REMATCH
    __sel="$(brow -q "title,url" -c | dmenu -i -f -l 10)"
    [[ "$__sel" =~ http.*$ ]] && echo "$BASH_REMATCH" | xargs -r -d '\n' brave
}
